services:
  - type: web
    name: office-agent
    env: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 18.19.1
      - key: PUPPETEER_SKIP_CHROMIUM_DOWNLOAD
        value: "false"
      - key: PUPPETEER_EXECUTABLE_PATH
        value: "/usr/bin/google-chrome" 